<?php


namespace Sm\Data\Entity\Property;


use Sm\Core\Context\Context;
use Sm\Data\Entity\Property\Validation\EntityPropertyValidationResult;
use Sm\Data\Evaluation\Validation\ValidationResult;
use Sm\Data\Property\Property;
use Sm\Data\Property\Validation\PropertyValidationResult;
use Sm\Data\Type\String_;

class EntityProperty extends Property implements EntityPropertySchema {
	protected function getValidationResult(...$arguments): PropertyValidationResult {
		return new EntityPropertyValidationResult(...$arguments);
	}
	/**
	 * @param \Sm\Core\Context\Context|null $context
	 *
	 * @return null|\Sm\Data\Evaluation\Validation\ValidationResult
	 * @throws \Sm\Core\Exception\UnimplementedError
	 */
	public function validate(Context $context = null): ?ValidationResult {
		$parent = parent::validate($context); // TODO: Change the autogenerated stub
		if (!isset($parent)) {
			$resolved_value = $this->resolve();
			$datatype       = $this->getPrimaryDatatype();
			/** @var \Sm\Data\Entity\Property\EntityPropertySchematic $schematic */
			$schematic = $this->getEffectiveSchematic();


			if ($schematic instanceof EntityPropertySchematic) {
				$minLength = $schematic ? $schematic->getMinLength() : null;
				if (isset($minLength) && $datatype instanceof String_ && strlen($resolved_value) < $minLength) {
					return $this->getValidationResult(false, 'Too short - must be at least ' . $minLength . ' characters');
				}
			}
		}
		return $parent;
	}
	public function jsonSerialize() {
		$value = $this->value;
		if ($value instanceof \DateTime) {
			return $value->format(DATE_ISO8601);
		} else {
			return parent::jsonSerialize();
		}
	}
}