#!/bin/bash

mkdir -p ../sites/alpha/{
    app/{
        config/{
            autoload,
            routes/dev,
            models/dev,
            sources/dev
        },
        view/{react,twig}
    },
    public/{js,css},
    scripts/config,
    src/Controller,
    test,
    storage/app/{
        cache,
        compiled
    }
}

&&

touch ../sites/alpha/{
    app/{
        config/{
            autoload/autoload.php,
            models/models.json,
            routes/routes.{json,php},
            sources/sources.json
        },
        src/{Controller/HomeController.php}
    }
}