<?php


namespace Sm\Data\Property\Validation;


use Sm\Data\Evaluation\Validation\ValidationResult;

class PropertyValidationResult extends ValidationResult {
    public function jsonSerialize() {
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
    
}